// import type { Metadata } from "next";
// import { Nunito_Sans } from "next/font/google";
// import "./globals.css";

// const nunitoSans = Nunito_Sans({
//   variable: "--font-nunito-sans",
//   subsets: ["latin"],
// });

// const nunitoSanss = Nunito_Sans({
//   variable: "--font-nunito-sans",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Fridge Raid",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${nunitoSans.variable} ${nunitoSans.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google"; 
import "./globals.css";

// Font configuration
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "Fridge Raid", // Tumhare app ka naam
  description: "Transform scattered ingredients into delicious personalized meals instantly.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
